# Generated by Django 4.0.5 on 2022-06-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('button_text', models.CharField(max_length=30)),
                ('photo', models.ImageField(upload_to='slider/%Y/%m')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
