# Generated by Django 4.0.5 on 2022-07-01 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=200)),
                ('fb_link', models.CharField(max_length=200)),
                ('linkedin_link', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='media/team/%Y/%m')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='slider',
            name='photo',
            field=models.ImageField(upload_to='media/slider/%Y/%m'),
        ),
    ]
