# Generated by Django 4.0.5 on 2022-07-04 03:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='desc',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
